{
  "swagger": "2.0",
  "info": {
    "description": "Solution of homework for NI-AM1 subject.\n",
    "version": "1.0.0",
    "title": "AM1 - Travel Agency",
    "contact": {
      "email": "chvostom@fit.cvut.cz"
    }
  },
  "host": "t-a.org",
  "basePath": "/",
  "tags": [
    {
      "name": "customer",
      "description": "All services about customers"
    },
    {
      "name": "tour",
      "description": "All services about tours"
    },
    {
      "name": "location",
      "description": "All services about locations"
    },
    {
      "name": "country",
      "description": "All services about countries"
    }
  ],
  "schemes": [
    "http"
  ],
  "paths": {
    "/customer": {
      "get": {
        "tags": [
          "customer"
        ],
        "summary": "Get all customers",
        "operationId": "getCustomers",
        "security": [
          {
            "travelagency_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "customer"
        ],
        "summary": "Add a new customer to travel agency database",
        "operationId": "addCustomer",
        "security": [
          {
            "travelagency_auth": [
              "write:customers",
              "read:customers"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "customer"
        ],
        "summary": "Update an existing customer",
        "operationId": "updateCustomer",
        "security": [
          {
            "travelagency_auth": [
              "write:customers",
              "read:customers"
            ]
          }
        ]
      }
    },
    "/customer/{customerId}": {
      "get": {
        "tags": [
          "customer"
        ],
        "summary": "Find customer by ID",
        "description": "Returns a single customer",
        "operationId": "getCustomerById",
        "security": [
          {
            "travelagency_auth": [
              "read:customers"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "customer"
        ],
        "summary": "Deletes a customer",
        "operationId": "deleteCustomer",
        "security": [
          {
            "travelagency_auth": [
              "write:customers",
              "read:customers"
            ]
          }
        ]
      }
    },
    "/tour": {
      "get": {
        "tags": [
          "tour"
        ],
        "summary": "Get all tours",
        "operationId": "getTours",
        "security": [
          {
            "travelagency_auth": [
              "read:tours"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "tour"
        ],
        "summary": "Add a new tour to travel agency database",
        "operationId": "addTour",
        "security": [
          {
            "travelagency_auth": [
              "write:tours",
              "read:tours"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "tour"
        ],
        "summary": "Update an existing tour",
        "operationId": "updateTour",
        "security": [
          {
            "travelagency_auth": [
              "write:tours",
              "read:tours"
            ]
          }
        ]
      }
    },
    "/tour/{tourId}": {
      "get": {
        "tags": [
          "tour"
        ],
        "summary": "Find tour by ID",
        "description": "Returns a single tour",
        "operationId": "getTourById",
        "security": [
          {
            "travelagency_auth": [
              "read:tours"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "tour"
        ],
        "summary": "Deletes a tour",
        "operationId": "deleteTour",
        "security": [
          {
            "travelagency_auth": [
              "write:tours",
              "read:tours"
            ]
          }
        ]
      }
    },
    "/tour/findByCustomer": {
      "get": {
        "tags": [
          "tour"
        ],
        "summary": "Finds tours by customer",
        "operationId": "findToursByCustomer",
        "security": [
          {
            "travelagency_auth": [
              "read:tours"
            ]
          }
        ]
      }
    },
    "/tour/findByLocation": {
      "get": {
        "tags": [
          "tour"
        ],
        "summary": "Finds tours by location",
        "operationId": "findToursByLocation",
        "security": [
          {
            "travelagency_auth": [
              "read:tours"
            ]
          }
        ]
      }
    },
    "/location": {
      "get": {
        "tags": [
          "location"
        ],
        "summary": "Get all locations",
        "operationId": "getLocations",
        "security": [
          {
            "travelagency_auth": [
              "read:locations"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "location"
        ],
        "summary": "Add a new location to travel agency database",
        "operationId": "addLocation",
        "security": [
          {
            "travelagency_auth": [
              "write:locations",
              "read:locations"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "location"
        ],
        "summary": "Update an existing location",
        "operationId": "updateLocation",
        "security": [
          {
            "travelagency_auth": [
              "write:locations",
              "read:locations"
            ]
          }
        ]
      }
    },
    "/location/{locationId}": {
      "get": {
        "tags": [
          "location"
        ],
        "summary": "Find location by ID",
        "description": "Returns a single location",
        "operationId": "getLocationById",
        "security": [
          {
            "travelagency_auth": [
              "read:locations"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "location"
        ],
        "summary": "Deletes a location",
        "operationId": "deleteLocation",
        "security": [
          {
            "travelagency_auth": [
              "write:locations",
              "read:locations"
            ]
          }
        ]
      }
    },
    "/country": {
      "get": {
        "tags": [
          "country"
        ],
        "summary": "Get all countries",
        "operationId": "getCountries",
        "security": [
          {
            "travelagency_auth": [
              "read:countries"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "country"
        ],
        "summary": "Add a new country to travel agency database",
        "operationId": "addCountry",
        "security": [
          {
            "travelagency_auth": [
              "write:countries",
              "read:countries"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "country"
        ],
        "summary": "Update an existing country",
        "operationId": "updateCountry",
        "security": [
          {
            "travelagency_auth": [
              "write:countries",
              "read:countries"
            ]
          }
        ]
      }
    },
    "/country/{countryId}": {
      "get": {
        "tags": [
          "country"
        ],
        "summary": "Find country by ID",
        "description": "Returns a single country",
        "operationId": "getCountryById",
        "security": [
          {
            "travelagency_auth": [
              "read:countries"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "country"
        ],
        "summary": "Deletes a country",
        "operationId": "deleteCountry",
        "security": [
          {
            "travelagency_auth": [
              "write:countries",
              "read:countries"
            ]
          }
        ]
      }
    }
  },
  "securityDefinitions": {
    "travelagency_auth": {
      "type": "oauth2",
      "authorizationUrl": "http://travelagency.swagger.io/oauth/dialog",
      "flow": "implicit",
      "scopes": {
        "write:customers": "modify customers in your account",
        "read:customers": "read your customers",
        "write:tours": "modify tour in your account",
        "read:tours": "read your tours",
        "write:locations": "modify locations in your account",
        "read:locations": "read your locations",
        "write:countries": "modify countries in your account",
        "read:countries": "read your countries"
      }
    }
  }
}